### ISSUE TITLE
Root credential rotate

### ISSUE THREAD

**Issue by twmcelroy** [hashicorp/vault-plugin-database-oracle#39]
When running Rotate root credential, the minimum password requirements don't line up. This was found by me and @efierro

Oracle Database Cloud Service on OCI
Oracle DB Version: 19.7.0.0
![image](https://user-images.githubusercontent.com/20779080/90448757-a45fe980-e0ab-11ea-93d9-7fe4f3a1ffe1.png)

It appears with the stringent password requirements of 19, the password creation in the plugin does not have 2 special characters. We had to remove the password requirements. Even when dropping the requirement to 12c, it did not work.
![image](https://user-images.githubusercontent.com/20779080/90450920-5bf6fa80-e0b0-11ea-95d1-a76f105637d1.png)

**Comment by pcman312** [comment]
Hi @twmcelroy ! This problem is fixed in Vault 1.6 & Oracle (plugin) 0.3 with the introduction of [password policies](https://www.vaultproject.io/docs/concepts/password-policies). Since each database, different versions of a database, and different configuration for a given database have different requirements for password structure, we introduced the ability to customize how a password is generated. The default remains the same as previously for backwards compatibility with existing systems, but you can set up a new password policy to match your own specific requirements.

**Comment by efierro** [comment]
Good to know, thanks. No need to change the profile or password function now by matching the Vault policy to the DB policy.
