### ISSUE TITLE
username_template usage

### ISSUE THREAD

**Issue by holiiveira** [hashicorp/vault-plugin-database-oracle#64]
i'm trying to use the `username_template`, like this:

```
vault write database/pctm/config/oracle-pctm \
    plugin_name=vault-plugin-database-oracle \
    connection_url="..." \
    allowed_roles="*" \
    username_template="token-{{.RoleName}}-{{unix_time}}-{{random 8}}" \
    username="..." \
    password="..."
```

and i get the following error:

```
Code: 500. Errors:

* 1 error occurred:
        * unable to create new user: rpc error: code = Internal desc = unable to create new user: failed to execute query: ORA-00922: missing or invalid option
```

this is the correct way to use it, am i doing something wrong?

**Comment by pcman312** [comment]
Hi @holiiveira ! The error `ORA-00922: missing or invalid option` usually indicates there's a problem with the SQL statements in some form. Based on your username template, the username that will be generated will include lowercase letters and dashes, which Oracle doesn't like unless you're very explicit about them.

For instance:
`CREATE USER token-foo-123-zv89u3ta WITH PASSWORD 'foobar';` will error because Oracle doesn't like the dashes in the username.

If you change it to:
`CREATE USER token_foo_123_zv89u3ta WITH PASSWORD 'foobar';` it will end up creating the user `TOKEN_FOO_123_ZV89U3TA` because Oracle will automatically uppercase the username unless you explicitly put single quotes around the username. For instance:
`CREATE USER 'token_foo_123_zv89u3ta' WITH PASSWORD 'foobar';` will create the user `token_foo_123_zv89u3ta`.
You can also create a user with dashes, but only if you include single quotes around the username.

You have a couple of options for your configuration:

**Option 1:**
Alter your custom username template to use underscores instead of dashes and uppercase the entire username:
`{{ printf "token_%s_%s_%s" (.RoleName) (unix_time) (random 8) | replace "-" "_" | uppercase }}`
Note: This is replacing dashes with underscores in case the role name has any dashes in it

This is the simplest option with the fewest potential problems.

**Option 2:**
Alter all of the statements to include single quotes around the username:
Example: `CREATE USER '{{username}}' WITH PASSWORD '{{password}}'`
IMPORTANT: If you take this approach, you will need to update `revocation_statements` with the same change because otherwise Vault will attempt to drop an uppercase user (`TOKEN_FOO_123_ZV89U3TA`) instead of the lowercase user that was actually created (`token_foo_123_zv89u3ta`) which will leave dangling users around.

If you do take this approach, I recommend also changing the other statements from their defaults to include single quotes around the usernames in case it becomes an issue in the future.
